// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBt-pPaX8rXR3ny0ziP5OxAfE4rGA7seJI',
    appId: '1:399563809198:web:3fbb8ef7ae4ef00c14a83f',
    messagingSenderId: '399563809198',
    projectId: 'fluttertest-4b3b5',
    authDomain: 'fluttertest-4b3b5.firebaseapp.com',
    storageBucket: 'fluttertest-4b3b5.appspot.com',
    measurementId: 'G-286TDGSW0R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATD-9B5NMqeehZZ3xnKJPm26q3spdHiHM',
    appId: '1:399563809198:android:ee576dcef832868514a83f',
    messagingSenderId: '399563809198',
    projectId: 'fluttertest-4b3b5',
    storageBucket: 'fluttertest-4b3b5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0evEFH9xOJtFvSOPi6OgsBB1sP4M0x9w',
    appId: '1:399563809198:ios:b62bf3aa74dbea8514a83f',
    messagingSenderId: '399563809198',
    projectId: 'fluttertest-4b3b5',
    storageBucket: 'fluttertest-4b3b5.appspot.com',
    iosBundleId: 'com.example.firebaseCrud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0evEFH9xOJtFvSOPi6OgsBB1sP4M0x9w',
    appId: '1:399563809198:ios:a7831f7f9ce174f514a83f',
    messagingSenderId: '399563809198',
    projectId: 'fluttertest-4b3b5',
    storageBucket: 'fluttertest-4b3b5.appspot.com',
    iosBundleId: 'com.example.firebaseCrud.RunnerTests',
  );
}
